
// 1.Find all the topics and tasks which are thought in the month of October

       db.collection.find({})

// Result:
/* 
[
    {
      _id: "6436512df3c5cbf2e5919f48",
      users: "A",
      codekata: "25",
      attendance: "present",
      topics: "javascript",
      tasks: "submitted",
      companydrives: "Tcs",
      placement: "not_appeared",
      date: "02-oct-2020",
      "mentee'scount": "20",
    },
    {
      _id: "6436512df3c5cbf2e5919f49",
      users: "B",
      codekata: "16",
      attendance: "absent",
      topics: "React",
      tasks: "submitted",
      company_drives: "Tcs",
      placement: "not appeared",
      date: "02-oct-2020",
      "mentee's_count": 20,
    },
    {
      _id: "6436512df3c5cbf2e5919f4a",
      users: "C",
      codekata: "34",
      attendance: "present",
      topics: "Angular",
      tasks: "not submitted",
      company_drives: "Google",
      placement: "not appeared",
      "mentee's_count": 20,
      date: "03-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f4b",
      users: "D",
      codekata: "23",
      attendance: "absent",
      topics: "MongoDB",
      tasks: " submitted",
      company_drives: "A1 soft",
      placement: "appeared",
      "mentee's_count": 20,
      date: "04-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f4c",
      users: "E",
      codekata: "61",
      attendance: "present",
      topics: "javascript",
      tasks: "submitted",
      company_drives: "Ramco systems",
      placement: "appeared",
      "mentee's_count": 20,
      date: "05-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f4d",
      users: "F",
      codekata: "54",
      attendance: "present",
      topics: "React",
      tasks: "not submitted",
      company_drives: "Amazon",
      placement: "not appeared",
      "mentee's_count": 20,
      date: "06-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f4e",
      users: "G",
      codekata: "38",
      attendance: "present",
      topics: "Angular",
      tasks: "submitted",
      company_drives: "IBM",
      placement: "appeared",
      "mentee's_count": 20,
      date: "07-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f4f",
      users: "H",
      codekata: "40",
      attendance: "present",
      topics: "MySQL",
      tasks: "not submitted",
      company_drives: "Oracle",
      placement: "appeared",
      "mentee's_count": 20,
      date: "08-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f50",
      users: "I",
      codekata: "58",
      attendance: "present",
      topics: "nodejs",
      tasks: "submitted",
      company_drives: "JMC",
      placement: "not appeared",
      "mentee's_count": 20,
      date: "09-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f51",
      users: "J",
      codekata: "49",
      attendance: "present",
      topics: "HTML",
      tasks: "submitted",
      company_drives: "Apple",
      placement: "appeared",
      "mentee's_count": 20,
      date: "10-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f52",
      users: "K",
      codekata: "67",
      attendance: "present",
      topics: "CSS",
      tasks: "not submitted",
      company_drives: "CTS",
      placement: "appeared",
      "mentee's_count": 20,
      date: "11-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f53",
      users: "L",
      codekata: "83",
      attendance: "present",
      topics: "Bootstrap",
      tasks: "submitted",
      company_drives: "L&T",
      placement: "appeared",
      "mentee's_count": 20,
      date: "12-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f54",
      users: "M",
      codekata: "39",
      attendance: "present",
      topics: "javascript",
      tasks: "submitted",
      company_drives: "samsung",
      placement: "not appeared",
      "mentee's_count": 20,
      date: "13-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f55",
      users: "N",
      codekata: "90",
      attendance: "present",
      topics: "HTML",
      tasks: "not submitted",
      company_drives: "Flipkart",
      placement: "appeared",
      "mentee's_count": 20,
      date: "14-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f56",
      users: "O",
      codekata: "66",
      attendance: "present",
      topics: "CSS",
      tasks: "submitted",
      company_drives: "Zomato",
      placement: "not appeared",
      "mentee's_count": 20,
      date: "15-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f57",
      users: "P",
      codekata: "65",
      attendance: "present",
      topics: "React",
      tasks: "not submitted",
      company_drives: "Google",
      placement: "appeared",
      "mentee's_count": 20,
      date: "16-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f58",
      users: "Q",
      codekata: "21",
      attendance: "present",
      topics: "CSS",
      tasks: "submitted",
      company_drives: "ABC",
      placement: "not appeared",
      "mentee's_count": 20,
      date: "17-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f59",
      users: "R",
      codekata: "35",
      attendance: "absent",
      topics: "Bootstrap",
      tasks: "not submitted",
      company_drives: "zentech",
      placement: "not appeared",
      "mentee's_count": 20,
      date: "18-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f5a",
      users: "S",
      codekata: "54",
      attendance: "present",
      topics: "Vuejs",
      tasks: "submitted",
      company_drives: "HP",
      placement: "appeared",
      "mentee's_count": 20,
      date: "19-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f5b",
      users: "T",
      codekata: "22",
      attendance: "present",
      topics: "javascript",
      tasks: "not submitted",
      company_drives: "Zomato",
      placement: "appeared",
      "mentee's_count": 20,
      date: "20-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f5c",
      users: "U",
      codekata: "33",
      attendance: "present",
      topics: "React",
      tasks: "submitted",
      company_drives: "straive",
      placement: "not appeared",
      "mentee's_count": 20,
      date: "21-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f5d",
      users: "V",
      codekata: "46",
      attendance: "present",
      topics: "nodejs",
      tasks: "not submitted",
      company_drives: "Sutherland",
      placement: "not appeared",
      "mentee's_count": 23,
      date: "22-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f5e",
      users: "W",
      codekata: "23",
      attendance: "present",
      topics: "MYSQL",
      tasks: "submitted",
      company_drives: "capegemini",
      placement: "appeared",
      "mentee's_count": 35,
      date: "23-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f5f",
      users: "X",
      codekata: "78",
      attendance: "absent",
      topics: "MongoDB",
      tasks: "not submitted",
      company_drives: "Zoho",
      placement: "not appeared",
      "mentee's_count": 12,
      date: "24-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f60",
      users: "Y",
      codekata: "100",
      attendance: "present",
      topics: "javascript",
      tasks: "submitted",
      company_drives: "Amazon",
      placement: "appeared",
      "mentee's_count": 31,
      date: "25-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f61",
      users: "Z",
      codekata: "76",
      attendance: "present",
      topics: "React",
      tasks: "not submitted",
      company_drives: "Apple",
      placement: "not appeared",
      "mentee's_count": 24,
      date: "26-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f62",
      users: "AA",
      codekata: "87",
      attendance: "present",
      topics: "Angular",
      tasks: "submitted",
      company_drives: "Microsoft",
      placement: "appeared",
      "mentee's_count": 10,
      date: "27-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f63",
      users: "BB",
      codekata: "45",
      attendance: "present",
      topics: "React",
      tasks: "submitted",
      company_drives: "Freshworks",
      placement: "not appeared",
      "mentee's_count": 20,
      date: "28-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f64",
      users: "CC",
      codekata: "46",
      attendance: "absent",
      topics: "javascript",
      tasks: "not submitted",
      company_drives: "Dell",
      placement: "appeared",
      "mentee's_count": 20,
      date: "29-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f65",
      users: "DD",
      codekata: "45",
      attendance: "present",
      topics: "nodejs",
      tasks: "submitted",
      company_drives: "capgemini",
      placement: "appeared",
      "mentee's_count": 2,
      date: "30-oct-2020",
    },
    {
      _id: "6436512df3c5cbf2e5919f66",
      users: "ED",
      codekata: "34",
      attendance: "present",
      topics: "React",
      tasks: "not submitted",
      company_drives: "CTS",
      placement: "not appeared",
      "mentee's_count": 8,
      date: "31-oct-2020",
    },
  ];
*/